module Evergreen.Migrate.V2 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Array
import AssocList
import Evergreen.V1.Internal.Model2
import Evergreen.V1.Internal.Teleport
import Evergreen.V1.SessionName
import Evergreen.V1.Types
import Evergreen.V1.Ui.Anim
import Evergreen.V2.Internal.Model2
import Evergreen.V2.Internal.Teleport
import Evergreen.V2.SessionName
import Evergreen.V2.Types
import Evergreen.V2.Ui.Anim
import Lamdera.Migrations exposing (..)
import List


frontendModel : Evergreen.V1.Types.FrontendModel -> ModelMigration Evergreen.V2.Types.FrontendModel Evergreen.V2.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V1.Types.BackendModel -> ModelMigration Evergreen.V2.Types.BackendModel Evergreen.V2.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V1.Types.FrontendMsg -> MsgMigration Evergreen.V2.Types.FrontendMsg Evergreen.V2.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V1.Types.ToBackend -> MsgMigration Evergreen.V2.Types.ToBackend Evergreen.V2.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V1.Types.BackendMsg -> MsgMigration Evergreen.V2.Types.BackendMsg Evergreen.V2.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V1.Types.ToFrontend -> MsgMigration Evergreen.V2.Types.ToFrontend Evergreen.V2.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_BackendModel : Evergreen.V1.Types.BackendModel -> Evergreen.V2.Types.BackendModel
migrate_Types_BackendModel old =
    { sessions = old.sessions |> migrate_AssocList_Dict migrate_SessionName_SessionName migrate_Types_Session
    }


migrate_AssocList_Dict : (a_old -> a_new) -> (b_old -> b_new) -> AssocList.Dict a_old b_old -> AssocList.Dict a_new b_new
migrate_AssocList_Dict migrate_a migrate_b old =
    old
        |> AssocList.toList
        |> List.map (Tuple.mapBoth migrate_a migrate_b)
        |> AssocList.fromList


migrate_Internal_Model2_Msg : Evergreen.V1.Internal.Model2.Msg -> Evergreen.V2.Internal.Model2.Msg
migrate_Internal_Model2_Msg old =
    case old of
        Evergreen.V1.Internal.Model2.Tick p0 ->
            Evergreen.V2.Internal.Model2.Tick p0

        Evergreen.V1.Internal.Model2.Teleported p0 p1 ->
            Evergreen.V2.Internal.Model2.Teleported (p0 |> migrate_Internal_Teleport_Trigger)
                (p1 |> migrate_Internal_Teleport_Event)


migrate_Internal_Model2_State : Evergreen.V1.Internal.Model2.State -> Evergreen.V2.Internal.Model2.State
migrate_Internal_Model2_State old =
    case old of
        Evergreen.V1.Internal.Model2.State p0 ->
            Evergreen.V2.Internal.Model2.State p0


migrate_Internal_Teleport_CssAnimation : Evergreen.V1.Internal.Teleport.CssAnimation -> Evergreen.V2.Internal.Teleport.CssAnimation
migrate_Internal_Teleport_CssAnimation old =
    old


migrate_Internal_Teleport_Data : Evergreen.V1.Internal.Teleport.Data -> Evergreen.V2.Internal.Teleport.Data
migrate_Internal_Teleport_Data old =
    case old of
        Evergreen.V1.Internal.Teleport.Css p0 ->
            Evergreen.V2.Internal.Teleport.Css (p0 |> migrate_Internal_Teleport_CssAnimation)

        Evergreen.V1.Internal.Teleport.ParentTrigger p0 ->
            Evergreen.V2.Internal.Teleport.ParentTrigger (p0 |> migrate_Internal_Teleport_ParentTriggerDetails)


migrate_Internal_Teleport_Event : Evergreen.V1.Internal.Teleport.Event -> Evergreen.V2.Internal.Teleport.Event
migrate_Internal_Teleport_Event old =
    { timestamp = old.timestamp
    , data = old.data |> List.map migrate_Internal_Teleport_Data
    }


migrate_Internal_Teleport_ParentTriggerDetails : Evergreen.V1.Internal.Teleport.ParentTriggerDetails -> Evergreen.V2.Internal.Teleport.ParentTriggerDetails
migrate_Internal_Teleport_ParentTriggerDetails old =
    old


migrate_Internal_Teleport_Trigger : Evergreen.V1.Internal.Teleport.Trigger -> Evergreen.V2.Internal.Teleport.Trigger
migrate_Internal_Teleport_Trigger old =
    case old of
        Evergreen.V1.Internal.Teleport.OnHover ->
            Evergreen.V2.Internal.Teleport.OnHover

        Evergreen.V1.Internal.Teleport.OnRender ->
            Evergreen.V2.Internal.Teleport.OnRender

        Evergreen.V1.Internal.Teleport.OnFocus ->
            Evergreen.V2.Internal.Teleport.OnFocus

        Evergreen.V1.Internal.Teleport.OnFocusWithin ->
            Evergreen.V2.Internal.Teleport.OnFocusWithin

        Evergreen.V1.Internal.Teleport.OnActive ->
            Evergreen.V2.Internal.Teleport.OnActive

        Evergreen.V1.Internal.Teleport.OnDismount ->
            Evergreen.V2.Internal.Teleport.OnDismount


migrate_SessionName_SessionName : Evergreen.V1.SessionName.SessionName -> Evergreen.V2.SessionName.SessionName
migrate_SessionName_SessionName old =
    case old of
        Evergreen.V1.SessionName.SessionName p0 ->
            Evergreen.V2.SessionName.SessionName p0


migrate_Types_BlurEvent : Evergreen.V1.Types.BlurEvent -> Evergreen.V2.Types.BlurEvent
migrate_Types_BlurEvent old =
    old


migrate_Types_CheckViewEvent : Evergreen.V1.Types.CheckViewEvent -> Evergreen.V2.Types.CheckViewEvent
migrate_Types_CheckViewEvent old =
    old


migrate_Types_ClickEvent : Evergreen.V1.Types.ClickEvent -> Evergreen.V2.Types.ClickEvent
migrate_Types_ClickEvent old =
    old


migrate_Types_Code : Evergreen.V1.Types.Code -> Evergreen.V2.Types.Code
migrate_Types_Code old =
    case old of
        Evergreen.V1.Types.UserCode p0 ->
            Evergreen.V2.Types.UserCode p0

        Evergreen.V1.Types.HttpRequestCode ->
            Evergreen.V2.Types.HttpRequestCode

        Evergreen.V1.Types.PortRequestCode ->
            Evergreen.V2.Types.PortRequestCode

        Evergreen.V1.Types.TestEntryPoint ->
            Evergreen.V2.Types.TestEntryPoint


migrate_Types_CommitStatus : Evergreen.V1.Types.CommitStatus -> Evergreen.V2.Types.CommitStatus
migrate_Types_CommitStatus old =
    case old of
        Evergreen.V1.Types.NotCommitted ->
            Evergreen.V2.Types.NotCommitted

        Evergreen.V1.Types.Committing p0 ->
            Evergreen.V2.Types.Committing p0

        Evergreen.V1.Types.CommitSuccess ->
            Evergreen.V2.Types.CommitSuccess

        Evergreen.V1.Types.CommitFailed ->
            Evergreen.V2.Types.CommitFailed


migrate_Types_ConnectEvent : Evergreen.V1.Types.ConnectEvent -> Evergreen.V2.Types.ConnectEvent
migrate_Types_ConnectEvent old =
    old


migrate_Types_Event : Evergreen.V1.Types.Event -> Evergreen.V2.Types.Event
migrate_Types_Event old =
    { isHidden = old.isHidden
    , timestamp = old.timestamp
    , eventType = old.eventType |> migrate_Types_EventType
    , clientId = old.clientId
    }


migrate_Types_EventType : Evergreen.V1.Types.EventType -> Evergreen.V2.Types.EventType
migrate_Types_EventType old =
    case old of
        Evergreen.V1.Types.KeyDown p0 ->
            Evergreen.V2.Types.KeyDown (p0 |> migrate_Types_KeyEvent)

        Evergreen.V1.Types.KeyUp p0 ->
            Evergreen.V2.Types.KeyUp (p0 |> migrate_Types_KeyEvent)

        Evergreen.V1.Types.Click p0 ->
            Evergreen.V2.Types.Click (p0 |> migrate_Types_ClickEvent)

        Evergreen.V1.Types.ClickLink p0 ->
            Evergreen.V2.Types.ClickLink (p0 |> migrate_Types_LinkEvent)

        Evergreen.V1.Types.Http p0 ->
            Evergreen.V2.Types.Http (p0 |> migrate_Types_HttpEvent)

        Evergreen.V1.Types.HttpLocal p0 ->
            Evergreen.V2.Types.HttpLocal (p0 |> migrate_Types_HttpLocalEvent)

        Evergreen.V1.Types.Connect p0 ->
            Evergreen.V2.Types.Connect (p0 |> migrate_Types_ConnectEvent)

        Evergreen.V1.Types.Paste p0 ->
            Evergreen.V2.Types.Paste (p0 |> migrate_Types_PasteEvent)

        Evergreen.V1.Types.Input p0 ->
            Evergreen.V2.Types.Input (p0 |> migrate_Types_InputEvent)

        Evergreen.V1.Types.ResetBackend ->
            Evergreen.V2.Types.ResetBackend

        Evergreen.V1.Types.FromJsPort p0 ->
            Evergreen.V2.Types.FromJsPort (p0 |> migrate_Types_FromJsPortEvent)

        Evergreen.V1.Types.WindowResize p0 ->
            Evergreen.V2.Types.WindowResize (p0 |> migrate_Types_WindowResizeEvent)

        Evergreen.V1.Types.PointerDown p0 ->
            Evergreen.V2.Types.PointerDown (p0 |> migrate_Types_PointerEvent)

        Evergreen.V1.Types.PointerUp p0 ->
            Evergreen.V2.Types.PointerUp (p0 |> migrate_Types_PointerEvent)

        Evergreen.V1.Types.PointerMove p0 ->
            Evergreen.V2.Types.PointerMove (p0 |> migrate_Types_PointerEvent)

        Evergreen.V1.Types.PointerLeave p0 ->
            Evergreen.V2.Types.PointerLeave (p0 |> migrate_Types_PointerEvent)

        Evergreen.V1.Types.PointerCancel p0 ->
            Evergreen.V2.Types.PointerCancel (p0 |> migrate_Types_PointerEvent)

        Evergreen.V1.Types.PointerOver p0 ->
            Evergreen.V2.Types.PointerOver (p0 |> migrate_Types_PointerEvent)

        Evergreen.V1.Types.PointerEnter p0 ->
            Evergreen.V2.Types.PointerEnter (p0 |> migrate_Types_PointerEvent)

        Evergreen.V1.Types.PointerOut p0 ->
            Evergreen.V2.Types.PointerOut (p0 |> migrate_Types_PointerEvent)

        Evergreen.V1.Types.TouchStart p0 ->
            Evergreen.V2.Types.TouchStart (p0 |> migrate_Types_TouchEvent)

        Evergreen.V1.Types.TouchCancel p0 ->
            Evergreen.V2.Types.TouchCancel (p0 |> migrate_Types_TouchEvent)

        Evergreen.V1.Types.TouchMove p0 ->
            Evergreen.V2.Types.TouchMove (p0 |> migrate_Types_TouchEvent)

        Evergreen.V1.Types.TouchEnd p0 ->
            Evergreen.V2.Types.TouchEnd (p0 |> migrate_Types_TouchEvent)

        Evergreen.V1.Types.CheckView p0 ->
            Evergreen.V2.Types.CheckView (p0 |> migrate_Types_CheckViewEvent)

        Evergreen.V1.Types.MouseDown p0 ->
            Evergreen.V2.Types.MouseDown (p0 |> migrate_Types_MouseEvent)

        Evergreen.V1.Types.MouseUp p0 ->
            Evergreen.V2.Types.MouseUp (p0 |> migrate_Types_MouseEvent)

        Evergreen.V1.Types.MouseMove p0 ->
            Evergreen.V2.Types.MouseMove (p0 |> migrate_Types_MouseEvent)

        Evergreen.V1.Types.MouseLeave p0 ->
            Evergreen.V2.Types.MouseLeave (p0 |> migrate_Types_MouseEvent)

        Evergreen.V1.Types.MouseOver p0 ->
            Evergreen.V2.Types.MouseOver (p0 |> migrate_Types_MouseEvent)

        Evergreen.V1.Types.MouseEnter p0 ->
            Evergreen.V2.Types.MouseEnter (p0 |> migrate_Types_MouseEvent)

        Evergreen.V1.Types.MouseOut p0 ->
            Evergreen.V2.Types.MouseOut (p0 |> migrate_Types_MouseEvent)

        Evergreen.V1.Types.Focus p0 ->
            Evergreen.V2.Types.Focus (p0 |> migrate_Types_FocusEvent)

        Evergreen.V1.Types.Blur p0 ->
            Evergreen.V2.Types.Blur (p0 |> migrate_Types_BlurEvent)


migrate_Types_FocusEvent : Evergreen.V1.Types.FocusEvent -> Evergreen.V2.Types.FocusEvent
migrate_Types_FocusEvent old =
    old


migrate_Types_FromJsPortEvent : Evergreen.V1.Types.FromJsPortEvent -> Evergreen.V2.Types.FromJsPortEvent
migrate_Types_FromJsPortEvent old =
    old


migrate_Types_FrontendModel : Evergreen.V1.Types.FrontendModel -> Evergreen.V2.Types.FrontendModel
migrate_Types_FrontendModel old =
    case old of
        Evergreen.V1.Types.LoadingSession p0 ->
            Evergreen.V2.Types.LoadingSession (p0 |> migrate_Types_LoadingData)

        Evergreen.V1.Types.LoadedSession p0 ->
            Evergreen.V2.Types.LoadedSession (p0 |> migrate_Types_LoadedData)


migrate_Types_FrontendMsg : Evergreen.V1.Types.FrontendMsg -> Evergreen.V2.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V1.Types.UrlClicked p0 ->
            Evergreen.V2.Types.UrlClicked p0

        Evergreen.V1.Types.UrlChanged p0 ->
            Evergreen.V2.Types.UrlChanged p0

        Evergreen.V1.Types.PressedResetSession ->
            Evergreen.V2.Types.PressedResetSession

        Evergreen.V1.Types.GotRandomSessionName p0 ->
            Evergreen.V2.Types.GotRandomSessionName (p0 |> migrate_SessionName_SessionName)

        Evergreen.V1.Types.ScrolledToBottom ->
            Evergreen.V2.Types.ScrolledToBottom

        Evergreen.V1.Types.MouseDownOnEvent p0 p1 ->
            Evergreen.V2.Types.MouseDownOnEvent p0 p1

        Evergreen.V1.Types.MouseEnterOnEvent p0 p1 ->
            Evergreen.V2.Types.MouseEnterOnEvent p0 p1

        Evergreen.V1.Types.ElmUiMsg p0 ->
            Evergreen.V2.Types.ElmUiMsg (p0 |> migrate_Ui_Anim_Msg)

        Evergreen.V1.Types.ToggledIncludeScreenPos p0 ->
            Evergreen.V2.Types.ToggledIncludeScreenPos p0

        Evergreen.V1.Types.ToggledIncludeClientPos p0 ->
            Evergreen.V2.Types.ToggledIncludeClientPos p0

        Evergreen.V1.Types.ToggledIncludePagePos p0 ->
            Evergreen.V2.Types.ToggledIncludePagePos p0

        Evergreen.V1.Types.MouseUpEvent ->
            Evergreen.V2.Types.MouseUpEvent

        Evergreen.V1.Types.PressedEvent ->
            Evergreen.V2.Types.PressedEvent

        Evergreen.V1.Types.GotFile p0 ->
            Evergreen.V2.Types.GotFile p0

        Evergreen.V1.Types.PressedSelectFile ->
            Evergreen.V2.Types.PressedSelectFile

        Evergreen.V1.Types.PressedNewFile ->
            Evergreen.V2.Types.PressedNewFile

        Evergreen.V1.Types.PressedCommitToFile ->
            Evergreen.V2.Types.PressedCommitToFile

        Evergreen.V1.Types.FileApiNotSupportedFromPort ->
            Evergreen.V2.Types.FileApiNotSupportedFromPort

        Evergreen.V1.Types.ToggledShowAllCode p0 ->
            Evergreen.V2.Types.ToggledShowAllCode p0

        Evergreen.V1.Types.WroteToFile p0 ->
            Evergreen.V2.Types.WroteToFile p0

        Evergreen.V1.Types.PressedDownloadTestGen ->
            Evergreen.V2.Types.PressedDownloadTestGen


migrate_Types_HttpEvent : Evergreen.V1.Types.HttpEvent -> Evergreen.V2.Types.HttpEvent
migrate_Types_HttpEvent old =
    old


migrate_Types_HttpLocalEvent : Evergreen.V1.Types.HttpLocalEvent -> Evergreen.V2.Types.HttpLocalEvent
migrate_Types_HttpLocalEvent old =
    old


migrate_Types_InputEvent : Evergreen.V1.Types.InputEvent -> Evergreen.V2.Types.InputEvent
migrate_Types_InputEvent old =
    old


migrate_Types_KeyEvent : Evergreen.V1.Types.KeyEvent -> Evergreen.V2.Types.KeyEvent
migrate_Types_KeyEvent old =
    old


migrate_Types_LinkEvent : Evergreen.V1.Types.LinkEvent -> Evergreen.V2.Types.LinkEvent
migrate_Types_LinkEvent old =
    old


migrate_Types_LoadedData : Evergreen.V1.Types.LoadedData -> Evergreen.V2.Types.LoadedData
migrate_Types_LoadedData old =
    { key = old.key
    , sessionName = old.sessionName |> migrate_SessionName_SessionName
    , history = old.history |> Array.map migrate_Types_Event
    , copyCounter = old.copyCounter
    , elmUiState = old.elmUiState |> migrate_Ui_Anim_State
    , settings = old.settings |> migrate_Types_Settings
    , parsedCode = old.parsedCode |> migrate_Types_ParsedCodeStatus
    , mouseDownOnEvent = old.mouseDownOnEvent
    , commitStatus = old.commitStatus |> migrate_Types_CommitStatus
    , noEventsHaveArrived = old.noEventsHaveArrived
    }


migrate_Types_LoadingData : Evergreen.V1.Types.LoadingData -> Evergreen.V2.Types.LoadingData
migrate_Types_LoadingData old =
    { key = old.key
    , sessionName = old.sessionName |> migrate_SessionName_SessionName
    }


migrate_Types_MouseEvent : Evergreen.V1.Types.MouseEvent -> Evergreen.V2.Types.MouseEvent
migrate_Types_MouseEvent old =
    old


migrate_Types_ParseError : Evergreen.V1.Types.ParseError -> Evergreen.V2.Types.ParseError
migrate_Types_ParseError old =
    case old of
        Evergreen.V1.Types.InvalidPortRequests ->
            Evergreen.V2.Types.InvalidPortRequests

        Evergreen.V1.Types.InvalidHttpRequests ->
            Evergreen.V2.Types.InvalidHttpRequests

        Evergreen.V1.Types.InvalidHttpAndPortRequests ->
            Evergreen.V2.Types.InvalidHttpAndPortRequests

        Evergreen.V1.Types.PortRequestsNotFound ->
            Evergreen.V2.Types.PortRequestsNotFound

        Evergreen.V1.Types.HttpRequestsNotFound ->
            Evergreen.V2.Types.HttpRequestsNotFound

        Evergreen.V1.Types.TestEntryPointNotFound ->
            Evergreen.V2.Types.TestEntryPointNotFound

        Evergreen.V1.Types.PortRequestsEndNotFound ->
            Evergreen.V2.Types.PortRequestsEndNotFound

        Evergreen.V1.Types.HttpRequestsEndNotFound ->
            Evergreen.V2.Types.HttpRequestsEndNotFound

        Evergreen.V1.Types.UnknownError ->
            Evergreen.V2.Types.UnknownError


migrate_Types_ParsedCode : Evergreen.V1.Types.ParsedCode -> Evergreen.V2.Types.ParsedCode
migrate_Types_ParsedCode old =
    { codeParts = old.codeParts |> List.map migrate_Types_Code
    , httpRequests = old.httpRequests
    , portRequests = old.portRequests
    , noPriorTests = old.noPriorTests
    }


migrate_Types_ParsedCodeStatus : Evergreen.V1.Types.ParsedCodeStatus -> Evergreen.V2.Types.ParsedCodeStatus
migrate_Types_ParsedCodeStatus old =
    case old of
        Evergreen.V1.Types.ParseSuccess p0 ->
            Evergreen.V2.Types.ParseSuccess (p0 |> migrate_Types_ParsedCode)

        Evergreen.V1.Types.ParseFailed p0 ->
            Evergreen.V2.Types.ParseFailed (p0 |> migrate_Types_ParseError)

        Evergreen.V1.Types.WaitingOnUser ->
            Evergreen.V2.Types.WaitingOnUser

        Evergreen.V1.Types.FileApiNotSupported ->
            Evergreen.V2.Types.FileApiNotSupported


migrate_Types_PasteEvent : Evergreen.V1.Types.PasteEvent -> Evergreen.V2.Types.PasteEvent
migrate_Types_PasteEvent old =
    old


migrate_Types_PointerEvent : Evergreen.V1.Types.PointerEvent -> Evergreen.V2.Types.PointerEvent
migrate_Types_PointerEvent old =
    old


migrate_Types_Session : Evergreen.V1.Types.Session -> Evergreen.V2.Types.Session
migrate_Types_Session old =
    { history = old.history |> Array.map migrate_Types_Event
    , connections = old.connections
    , settings = old.settings |> migrate_Types_Settings
    }


migrate_Types_Settings : Evergreen.V1.Types.Settings -> Evergreen.V2.Types.Settings
migrate_Types_Settings old =
    old


migrate_Types_ToFrontend : Evergreen.V1.Types.ToFrontend -> Evergreen.V2.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V1.Types.LoadSessionResponse p0 ->
            Evergreen.V2.Types.LoadSessionResponse
                { history = p0.history |> Array.map migrate_Types_Event
                , settings = p0.settings |> migrate_Types_Settings
                }

        Evergreen.V1.Types.SessionUpdate p0 ->
            Evergreen.V2.Types.SessionUpdate (p0 |> migrate_Types_Event)

        Evergreen.V1.Types.ResetSession ->
            Evergreen.V2.Types.ResetSession


migrate_Types_TouchEvent : Evergreen.V1.Types.TouchEvent -> Evergreen.V2.Types.TouchEvent
migrate_Types_TouchEvent old =
    old


migrate_Types_WindowResizeEvent : Evergreen.V1.Types.WindowResizeEvent -> Evergreen.V2.Types.WindowResizeEvent
migrate_Types_WindowResizeEvent old =
    old


migrate_Ui_Anim_Msg : Evergreen.V1.Ui.Anim.Msg -> Evergreen.V2.Ui.Anim.Msg
migrate_Ui_Anim_Msg old =
    old |> migrate_Internal_Model2_Msg


migrate_Ui_Anim_State : Evergreen.V1.Ui.Anim.State -> Evergreen.V2.Ui.Anim.State
migrate_Ui_Anim_State old =
    old |> migrate_Internal_Model2_State
